export const JOURNEY_STOPS = [
  {
    city: "Hamburg",
    country: "Germany",
    lat: 53.55,
    lng: 9.99,
    label: "Born",
  },
  {
    city: "Düsseldorf",
    country: "Germany",
    lat: 51.23,
    lng: 6.78,
    label: "Early childhood",
  },
  {
    city: "Cape Town",
    country: "South Africa",
    lat: -33.92,
    lng: 18.42,
    label: "Five years in South Africa",
  },
  {
    city: "New York City",
    country: "USA",
    lat: 40.71,
    lng: -74.01,
    label: "The Browning School, Grade 8",
  },
  {
    city: "Boca Raton",
    country: "USA",
    lat: 26.36,
    lng: -80.08,
    label: "Saint Andrew's School, Grades 9 and 10",
  },
  {
    city: "New York City",
    country: "USA",
    lat: 40.71,
    lng: -74.01,
    label: "The Browning School, Grades 11 and 12",
  },
  {
    city: "Austin",
    country: "USA",
    lat: 30.27,
    lng: -97.74,
    label: "UT Austin, McCombs School of Business",
  },
  {
    city: "Dallas",
    country: "USA",
    lat: 32.78,
    lng: -96.8,
    label: "SCA Health and Integrity HIT",
  },
  {
    city: "Austin",
    country: "USA",
    lat: 30.27,
    lng: -97.74,
    label: "Protea",
  },
] as const;
